using System.Collections;
using System.Text.Json.Serialization;

using Alethic.Auth0.Operator.Core.Extensions;
using Alethic.Auth0.Operator.Core.Models;
using Alethic.Auth0.Operator.Core.Models.LogStream;

using k8s.Models;

using KubeOps.Abstractions.Entities;
using KubeOps.Abstractions.Entities.Attributes;

namespace Alethic.Auth0.Operator.Models
{

    /// <summary>
    /// Represents an Auth0 LogStream resource in Kubernetes.
    /// LogStreams provide operational logging to 8 destination types.
    /// </summary>
    [EntityScope(EntityScope.Namespaced)]
    [KubernetesEntity(Group = "kubernetes.auth0.com", ApiVersion = "v1", Kind = "LogStream", PluralName = "logstreams")]
    [KubernetesEntityShortNames("a0ls")]
    public partial class V1LogStream :
        CustomKubernetesEntity<V1LogStream.SpecDef, V1LogStream.StatusDef>,
        V1TenantEntity<V1LogStream.SpecDef, V1LogStream.StatusDef, LogStreamConf>
    {

        public class SpecDef : V1TenantEntitySpec<LogStreamConf>
        {

            /// <summary>
            /// Set of operations allowed with the entity.
            /// Valid values: Create, Update, Delete
            /// </summary>
            [JsonPropertyName("policy")]
            public V1EntityPolicyType[]? Policy { get; set; }

            /// <summary>
            /// Reference to the Tenant resource that owns this log stream.
            /// </summary>
            [JsonPropertyName("tenantRef")]
            [Required]
            public V1TenantReference? TenantRef { get; set; }

            /// <summary>
            /// Criteria for finding existing Auth0 log streams to adopt.
            /// </summary>
            [JsonPropertyName("find")]
            public LogStreamFind? Find { get; set; }

            /// <summary>
            /// Initial configuration used only during log stream creation.
            /// Falls back to Conf if not specified.
            /// </summary>
            [JsonPropertyName("init")]
            public LogStreamConf? Init { get; set; }

            /// <summary>
            /// LogStream configuration matching Auth0 Management API schema.
            /// </summary>
            [JsonPropertyName("conf")]
            [Required]
            public LogStreamConf? Conf { get; set; }

        }

        public class StatusDef : V1TenantEntityStatus
        {

            /// <summary>
            /// Auth0 LogStream ID (format: lst_XXXXX)
            /// </summary>
            [JsonPropertyName("id")]
            public string? Id { get; set; }

            /// <summary>
            /// Current status of the log stream: active, paused, suspended.
            /// </summary>
            [JsonPropertyName("currentStatus")]
            public string? CurrentStatus { get; set; }

            /// <summary>
            /// The type of log stream destination.
            /// </summary>
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            /// <summary>
            /// AWS Partner Event Source ARN for EventBridge log streams.
            /// This is auto-generated by Auth0 when creating an EventBridge log stream
            /// and follows the pattern: aws.partner/auth0.com/{tenant-name}-{uuid}/auth0.logs
            /// Consumers need this value to create EventBridge rules that route logs to their targets.
            /// </summary>
            [JsonPropertyName("awsPartnerEventSource")]
            public string? AwsPartnerEventSource { get; set; }

            /// <summary>
            /// Azure Partner Topic name for EventGrid log streams.
            /// This is auto-generated by Auth0 when creating an EventGrid log stream.
            /// Consumers need this value to create Azure Event Grid subscriptions.
            /// </summary>
            [JsonPropertyName("azurePartnerTopic")]
            public string? AzurePartnerTopic { get; set; }

            /// <summary>
            /// Last synced configuration state.
            /// </summary>
            [JsonPropertyName("lastConf")]
            [JsonConverter(typeof(SimplePrimitiveHashtableConverter))]
            public Hashtable? LastConf { get; set; }

        }

    }

}
