apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eventstreams.kubernetes.auth0.com
  annotations:
    api.kubernetes.auth0.com/status: "beta"
    api.kubernetes.auth0.com/note: "Auth0 EventStreams API is in Early Access"
spec:
  group: kubernetes.auth0.com
  names:
    kind: EventStream
    listKind: EventStreamList
    plural: eventstreams
    singular: eventstream
    shortNames:
      - a0es
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - tenantRef
                - conf
              properties:
                policy:
                  type: array
                  items:
                    type: string
                    enum:
                      - Create
                      - Update
                      - Delete
                tenantRef:
                  type: object
                  required:
                    - name
                  properties:
                    namespace:
                      type: string
                    name:
                      type: string
                find:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                init:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                conf:
                  type: object
                  properties:
                    name:
                      type: string
                    type:
                      type: string
                      enum:
                        - eventbridge
                        - webhook
                    status:
                      type: string
                      enum:
                        - active
                        - paused
                    subscriptions:
                      type: array
                      items:
                        type: object
                        properties:
                          eventType:
                            type: string
                            enum:
                              - user.created
                              - user.updated
                              - user.deleted
                              - organization.created
                              - organization.updated
                              - organization.deleted
                              - organization.member.added
                              - organization.member.deleted
                              - organization.member.role.assigned
                              - organization.member.role.deleted
                              - organization.connection.added
                              - organization.connection.updated
                              - organization.connection.removed
                    sink:
                      type: object
                      properties:
                        eventBridge:
                          type: object
                          properties:
                            awsAccountId:
                              type: string
                            awsRegion:
                              type: string
                        webhook:
                          type: object
                          properties:
                            url:
                              type: string
                            authorizationSecretRef:
                              type: object
                              properties:
                                name:
                                  type: string
                                key:
                                  type: string
            status:
              type: object
              properties:
                id:
                  type: string
                currentStatus:
                  type: string
                type:
                  type: string
                subscribedEvents:
                  type: array
                  items:
                    type: string
                lastConf:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Id
          type: string
          jsonPath: .status.id
        - name: Type
          type: string
          jsonPath: .status.type
        - name: Status
          type: string
          jsonPath: .status.currentStatus
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
